version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nginx_1
      - nginx_2

  nginx_1:
    image: nginx
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: "/feature-1"

  nginx_2:
    image: nginx
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: "/feature-2"
